# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configure Dependabot for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  # Configure Dependabot for each package in the Rush monorepo
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm"
    directory: "/packages/create"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/metadata"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm"
    directory: "/packages/server"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm"
    directory: "/packages/server-infrastructure"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm"
    directory: "/tools/eslint-config"
    schedule:
      interval: "daily"
      
  # Website package
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"